language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3.5"

env:
  global:
    - SECRET_KEY=m9rOHQCtrsuhppNu4oez8woU
    - JWT_AUTH_URL_RULE=/v1/auth
    - FLASK_APP=app.py
    - FLASK_ENV=development
    - FLASK_DEBUG=0

install:
  - pip install -r requirements/dev.txt

before_script:
  - flask run &

script:
  - sleep 2 && py.test -v